### ISSUE TITLE
Questions regarding the code

### ISSUE THREAD

**Issue by muslll** [Dreamzz5/Simple-Align#3]
Hi, thanks for your research. The code is a bit unclear to me, so I thought about asking some questions:
- Why self.lq [seems](https://github.com/Dreamzz5/Simple-Align/blob/main/realesrgan/data/realesrgan_dataset.py#L169) to [need](https://github.com/Dreamzz5/Simple-Align/blob/main/realesrgan/models/realesrnet_model.py#L86) kernel3 and kernel4, when the option dict is neither [present](https://github.com/Dreamzz5/Simple-Align/blob/main/options/train/train_realsrresnet_reg.yml#L63) nor [parsed](https://github.com/Dreamzz5/Simple-Align/blob/main/realesrgan/data/realesrgan_dataset.py#L53) for that option? Edit: it looks like kernel3 is a random.choice of kernel, and kernel4 is a random.choice of kernel2?
- Why [repeat](https://github.com/Dreamzz5/Simple-Align/blob/main/realesrgan/models/realesrnet_model.py#L176) the self.gt image 2 times? Is that needed to align GT1-GT2/LQ1-LQ2?
- On [this line](https://github.com/Dreamzz5/Simple-Align/blob/main/realesrgan/models/realesrnet_model.py#L218), is `self.net_g.out` correct? Or is that meant to be `self.output` (generator prediction based on the generated LQs)?

Thanks in advance.

**Comment by Dreamzz5** [comment]
1. `kernel3` and `kernel4` are prepared for the second expansion, so `kernel3` is a `random.choice` of `kernel`, and `kernel4` is a `random.choice` of `kernel2`.
2. Repeating GT twice is because the two expansions have the same GT.
3. `self.net_g.out` is correct. Please refer to the RDSR code and paper. What we aim for is a network representation that is insensitive to degradation.

**Comment by muslll** [comment]
Thanks :+1:
